# [[language]]
# name = ""
# scope = "source.*"
# indent = { tab-width = 4, unit = "  " }

[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "c"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "\t"}

	

[[language]]
name = "toml"
indent = { tab-width = 4, unit = "\t" }


[rust.config]
checkOnSave = { command = "clippy" }
